/* Generated By:JavaCC: Do not edit this line. RustConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface RustConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int FN = 1;
  /** RegularExpression Id. */
  int MAIN = 2;
  /** RegularExpression Id. */
  int PRINTLN = 3;
  /** RegularExpression Id. */
  int APAREN = 4;
  /** RegularExpression Id. */
  int FPAREN = 5;
  /** RegularExpression Id. */
  int ACHAVES = 6;
  /** RegularExpression Id. */
  int FCHAVES = 7;
  /** RegularExpression Id. */
  int ACOLCHETE = 8;
  /** RegularExpression Id. */
  int FCOLCHETE = 9;
  /** RegularExpression Id. */
  int PONTOVIRGULA = 10;
  /** RegularExpression Id. */
  int VIRGULA = 11;
  /** RegularExpression Id. */
  int PONTO = 12;
  /** RegularExpression Id. */
  int ASPASDUPLAS = 13;
  /** RegularExpression Id. */
  int NUM = 14;
  /** RegularExpression Id. */
  int DECIMAL = 15;
  /** RegularExpression Id. */
  int CADEIA = 16;
  /** RegularExpression Id. */
  int CARACTERE = 17;
  /** RegularExpression Id. */
  int DOISPONTOS = 18;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"fn\"",
    "\"main\"",
    "\"println!\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"\\\"\"",
    "<NUM>",
    "<DECIMAL>",
    "<CADEIA>",
    "<CARACTERE>",
    "\":\"",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
  };

}
